apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-claim0
  namespace: 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: 
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: cast-service
        image: greglebreton/cast-service:latest
        command: ["uvicorn"]
        args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: DATABASE_URI
          value: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/
          name: cast-service-claim0
      volumes:
      - name: cast-service-claim0
        persistentVolumeClaim:
          claimName: cast-service-claim0
