apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-service-claim0
  namespace: 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: 
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: movie-service
        image: petitbou/movie-service:latest
        command: ["uvicorn"]
        args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: CAST_SERVICE_HOST_URL
          value: http://cast-service:8000/api/v1/casts/
        - name: DATABASE_URI
          value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/
          name: movie-service-claim0
      volumes:
      - name: movie-service-claim0
        persistentVolumeClaim:
          claimName: movie-service-claim0
