apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            defaultMode: 484
      containers:
        - name: nginx
          image: "nginx:latest"
          ports:
            - containerPort: 80

